// ── Gig Categories & Sub-types ──
// Single source of truth for all categories, skills, and gig types across the platform.

export interface GigCategory {
  slug: string;
  name: string;
  emoji: string;
  description: string;
  subTypes: string[];
}

export const GIG_CATEGORIES: GigCategory[] = [
  {
    slug: 'errands-delivery',
    name: 'Errands & Delivery',
    emoji: '🏃',
    description: 'Campus and local delivery, shopping runs, and quick errands',
    subTypes: [
      'Campus food delivery',
      'Package/parcel delivery',
      'Grocery shopping & delivery',
      'Pharmacy/medicine pickup',
      'Laundry pickup & drop-off',
      'Document/letter delivery',
      'Library book returns',
      'Post office runs',
      'Key pickup/drop-off',
      'Queue/line standing',
      'Fuel station runs',
      'Airtime/data top-up runs',
      'Market shopping',
      'Gift buying & delivery',
      'Printing & photocopying runs',
      'Water/gas cylinder refill & delivery',
      'Takeaway food pickup',
      'Dropping off rental returns',
      'Ticket purchasing',
    ],
  },
  {
    slug: 'typing-data-entry',
    name: 'Typing & Data Entry',
    emoji: '⌨️',
    description: 'Typing, transcription, spreadsheets, and document formatting',
    subTypes: [
      'Typing handwritten lecture notes',
      'Data entry into spreadsheets',
      'Form filling',
      'PDF to Word conversion',
      'Audio/video transcription',
      'Document formatting',
      'PowerPoint/slide creation',
      'Scanning & digitizing documents',
      'Data cleaning & organizing',
      'Address/contact list compilation',
      'Survey data entry & tabulation',
      'Receipt/invoice logging',
      'Invoice & receipt creation',
      'Email list building',
      'Database/record entry',
      'Copying text from images',
      'Converting paper records to digital',
      'Filling out application forms',
      'Typing up meeting minutes',
      'Index/catalogue creation',
    ],
  },
  {
    slug: 'event-support',
    name: 'Event Support & Ushering',
    emoji: '🎪',
    description: 'Ushering, event setup, registration, and cleanup',
    subTypes: [
      'Event ushering',
      'Registration desk attendant',
      'Stage/venue setup & breakdown',
      'Event decoration & styling',
      'Balloon arrangement',
      'Sound/speaker system setup helper',
      'Crowd management & direction',
      'Ticket checking/door control',
      'Gift bag assembly & distribution',
      'Event cleanup',
      'Drink/food serving',
      'MC/host for small events',
      'Coat/bag check attendant',
      'Name tag/badge preparation',
      'Guest list management',
      'Parking attendant/guide',
      'Photo booth operation',
      'Seating arrangement',
      'Program/schedule distribution',
    ],
  },
  {
    slug: 'childcare-petcare',
    name: 'Childcare & Pet Care',
    emoji: '👶',
    description: 'Babysitting, pet sitting, dog walking, and companion services',
    subTypes: [
      'Babysitting',
      'After-school child pickup',
      'Homework help for children',
      'Pet sitting',
      'Dog walking',
      'Pet feeding',
      'Playdate supervision',
      'Reading aloud to children',
      'School drop-off/pickup',
      'Weekend childminding',
      'Birthday party child supervision',
      'Toddler watching during events',
      'Pet grooming',
      'Elderly companion/helper',
    ],
  },
  {
    slug: 'tutoring-academic',
    name: 'Tutoring & Academic Help',
    emoji: '📚',
    description: 'Subject tutoring, exam prep, proofreading, and study help',
    subTypes: [
      'Maths tutoring',
      'Science tutoring',
      'English language tutoring',
      'French tutoring',
      'Reading & comprehension help',
      'Exam prep coaching',
      'Study group facilitation',
      'Assignment proofreading',
      'Research assistance',
      'Citation & reference formatting',
      'Thesis/project formatting',
      'Lab report writing assistance',
      'Presentation practice/coaching',
      'Essay editing & feedback',
      'Book/article summarizing',
      'Homework help',
      'ICT/computer basics tutoring',
      'Accounting/bookkeeping tutoring',
      'Local language tutoring',
      'IELTS/TOEFL prep help',
    ],
  },
  {
    slug: 'app-testing',
    name: 'App & Product Testing',
    emoji: '📱',
    description: 'App testing, website feedback, mystery shopping, and reviews',
    subTypes: [
      'Mobile app testing',
      'Website usability testing',
      'Game testing & feedback',
      'Physical product testing & review',
      'Food/beverage taste testing',
      'Mystery shopping',
      'User experience walkthrough',
      'Ad/commercial feedback',
      'Packaging/label review',
      'Brand name opinion testing',
      'Price comparison research',
      'Feature comparison testing',
      'Beta app bug reporting',
      'E-commerce checkout testing',
      'Chatbot/AI tool testing',
    ],
  },
  {
    slug: 'surveys-research',
    name: 'Surveys & Research',
    emoji: '📋',
    description: 'Campus surveys, data collection, focus groups, and market research',
    subTypes: [
      'Campus survey administration',
      'Door-to-door questionnaires',
      'Online survey completion',
      'Focus group participation',
      'Interview transcription',
      'Market research data collection',
      'Observation studies',
      'Phone survey caller',
      'Product preference polls',
      'Social media sentiment gathering',
      'Competitor price checking',
      'Location scouting/research',
      'Library/archive research',
      'Fact-checking & verification',
      'News/event monitoring',
    ],
  },
  {
    slug: 'flyer-distribution',
    name: 'Flyer & Poster Distribution',
    emoji: '📄',
    description: 'Flyer handouts, poster hanging, and promotional campaigns',
    subTypes: [
      'Flyer distribution (hand-to-hand)',
      'Poster hanging on notice boards',
      'Banner holding/human billboard',
      'Car windshield flyering',
      'Door-to-door leaflet drops',
      'Business card distribution',
      'QR code flyer posting',
      'Coupon/voucher handouts',
      'Event invitation distribution',
      'Menu distribution',
      'Campus billboard posting',
      'Sticker/decal placement',
      'Sandwich board wearing',
      'Digital flyer sharing',
    ],
  },
  {
    slug: 'cleaning-organizing',
    name: 'Cleaning & Organizing',
    emoji: '🧹',
    description: 'Room cleaning, organizing, car washing, and tidying up',
    subTypes: [
      'Room/apartment cleaning',
      'Office cleaning',
      'Closet/wardrobe organizing',
      'Garage/storeroom organizing',
      'Kitchen deep cleaning',
      'Bathroom cleaning',
      'Window washing',
      'Carpet/rug cleaning',
      'Fridge/freezer cleaning',
      'Decluttering assistance',
      'Desk/workspace organizing',
      'Post-event/post-party cleanup',
      'Trash/junk removal',
      'Book/shelf organizing',
      'Car interior cleaning & detailing',
      'Ironing & clothes folding',
      'Shoe cleaning & polishing',
      'Bed making & linen changing',
      'Dusting & surface wiping',
    ],
  },
  {
    slug: 'physical-manual',
    name: 'Physical & Manual Work',
    emoji: '💪',
    description: 'Moving, lifting, gardening, painting, and hands-on labor',
    subTypes: [
      'Moving/lifting help',
      'Furniture rearranging',
      'Loading/unloading trucks',
      'Gardening & weeding',
      'Lawn mowing & trimming',
      'Room painting',
      'Shelf/curtain mounting',
      'Picture/TV hanging',
      'Light bulb & fixture changing',
      'Water fetching & tank filling',
      'Carrying heavy items',
      'Fence painting',
      'Car washing (exterior)',
      'Tire changing assistance',
      'Sweeping compound/yard',
      'Clearing debris',
      'Packing & unpacking boxes',
      'Setting up canopy/tent',
      'Digging & planting',
      'Carrying market goods',
    ],
  },
  {
    slug: 'food-cooking',
    name: 'Food & Cooking',
    emoji: '🍳',
    description: 'Cooking, baking, meal prep, catering help, and kitchen tasks',
    subTypes: [
      'Cooking for small gatherings',
      'Meal prep & portioning',
      'Baking (cakes, bread, pastries)',
      'Food packaging & labeling',
      'Smoothie/juice making',
      'Catering assistant',
      'Dishwashing',
      'Kitchen helper/prep cook',
      'Food vendor assistant',
      'Barbecue/grill helper',
      'Serving at parties/dinners',
      'Food delivery (homemade)',
      'Snack preparation for events',
      'Tea/coffee service',
      'Market ingredient shopping & prep',
    ],
  },
  {
    slug: 'social-media',
    name: 'Social Media & Content',
    emoji: '📲',
    description: 'Social media management, content creation, and basic editing',
    subTypes: [
      'Instagram page management',
      'TikTok content creation',
      'Facebook page management',
      'Twitter/X posting & engagement',
      'WhatsApp broadcast management',
      'Basic photo editing',
      'Short video/reel editing',
      'Hashtag research & strategy',
      'Comment & DM responding',
      'Content scheduling & posting',
      'Creating Instagram stories',
      'Writing social media captions',
      'Reposting & engagement farming',
      'Creating simple graphics',
      'Influencer outreach/DMs',
    ],
  },
  {
    slug: 'photography-video',
    name: 'Photography & Video',
    emoji: '📸',
    description: 'Event photography, product shots, short videos, and livestreams',
    subTypes: [
      'Event photography',
      'Product photography',
      'Portrait/headshot photography',
      'Short promotional video recording',
      'Birthday/graduation recording',
      'Video testimonial recording',
      'Behind-the-scenes filming',
      'Before-and-after documentation',
      'Real estate/room photography',
      'Food photography',
      'Livestream setup & operation',
      'Graduation/occasion photoshoot',
    ],
  },
  {
    slug: 'writing-communication',
    name: 'Writing & Translation',
    emoji: '✍️',
    description: 'Letters, CVs, speeches, translations, and proofreading',
    subTypes: [
      'Letter/email drafting',
      'CV/resume writing',
      'Cover letter writing',
      'Speech/toast writing',
      'Social media bio writing',
      'Blog post/article writing',
      'Product description writing',
      'Invitation/announcement writing',
      'Thank you note writing',
      'WhatsApp marketing copy',
      'Petition/complaint drafting',
      'Translation (English ↔ local languages)',
      'Proofreading & grammar checking',
      'Creative writing',
      'Obituary/tribute writing',
    ],
  },
  {
    slug: 'basic-tech',
    name: 'Basic Tech & IT Support',
    emoji: '🖥️',
    description: 'Phone setup, Wi-Fi fixes, app installs, and basic troubleshooting',
    subTypes: [
      'Phone setup & data transfer',
      'Basic computer troubleshooting',
      'Printer setup & fixing',
      'Wi-Fi/router troubleshooting',
      'App installation & setup',
      'Software installation',
      'Email account setup',
      'Social media account creation',
      'Basic website content updates',
      'Online store product listing',
      'Google Workspace setup',
      'Zoom/Teams meeting setup',
      'Smart TV/streaming setup',
      'Antivirus installation',
      'File backup to cloud/drive',
    ],
  },
  {
    slug: 'sales-retail',
    name: 'Sales & Retail',
    emoji: '🏪',
    description: 'Shop help, ticket selling, inventory, and temporary retail roles',
    subTypes: [
      'Market stall helper',
      'Shop assistant (temporary)',
      'Ticket selling',
      'Hawking/street vending assistant',
      'Pop-up shop/stand assistant',
      'Cashier (temporary events)',
      'Stock taking & inventory counting',
      'Price tagging & labeling',
      'Product display & shelf stocking',
      'Customer greeting & assistance',
      'Cash counting & reconciliation',
      'Sample/taster distribution',
      'Order taking & processing',
      'Wrapping & bagging purchases',
      'Returns & exchange processing',
    ],
  },
  {
    slug: 'creative-craft',
    name: 'Creative & Design',
    emoji: '🎨',
    description: 'Gift wrapping, poster design, graphic design, and creative tasks',
    subTypes: [
      'Gift wrapping',
      'Card making & hand-lettering',
      'Poster/banner design',
      'T-shirt/tote bag printing help',
      'Face painting',
      'Henna/mehndi application',
      'Bead/jewelry making',
      'Craft workshop assistant',
      'Art class helper',
      'Scrapbook/photo album creation',
      'Custom sticker/label making',
      'Party prop creation',
      'Graphic design (Canva, Figma)',
      'Logo design',
      'UI/UX design',
    ],
  },
  {
    slug: 'transport-companion',
    name: 'Transport & Accompaniment',
    emoji: '🚗',
    description: 'Driving, airport runs, tours, and companion services',
    subTypes: [
      'Designated driver',
      'Airport pickup/drop-off companion',
      'Errand runner (okada/taxi)',
      'Elderly companion for outings',
      'Hospital visit accompaniment',
      'Shopping trip companion',
      'Campus tour guide',
      'City/area tour guide',
      'Walking/jogging partner',
    ],
  },
  {
    slug: 'office-admin',
    name: 'Office & Admin',
    emoji: '🗂️',
    description: 'Filing, photocopying, receptionist duties, and office tasks',
    subTypes: [
      'Filing & document sorting',
      'Photocopying & binding',
      'Receptionist (temporary)',
      'Phone answering & message taking',
      'Appointment scheduling',
      'Note-taking at meetings/lectures',
      'Envelope stuffing & mailing',
      'Mail sorting & delivery (internal)',
      'Office supplies restocking',
      'Calendar & schedule management',
      'Visitor check-in management',
      'Data archiving',
      'Label printing & applying',
      'File digitization & upload',
    ],
  },
  {
    slug: 'web-app-dev',
    name: 'Web & App Development',
    emoji: '💻',
    description: 'Website building, app development, and coding tasks',
    subTypes: [
      'Simple website creation',
      'WordPress setup & customization',
      'Landing page development',
      'Bug fixing & debugging',
      'Mobile app development',
      'API integration',
      'Database setup',
      'E-commerce store setup',
      'Website maintenance',
      'Code review & mentoring',
    ],
  },
  {
    slug: 'campus-specific',
    name: 'Campus Life',
    emoji: '🎓',
    description: 'Campus-specific tasks, orientation help, and university errands',
    subTypes: [
      'Lecture note sharing/selling',
      'Campus directions/orientation help',
      'Hostel room setup/decorating',
      'Club/society event helper',
      'SRC/election campaign helper',
      'Exam hall setup',
      'Registration/enrollment assistance',
      'Lost & found search helper',
      'Study space reservation',
      'Lab equipment setup/cleanup',
      'Library assistant (unofficial)',
      'Graduation ceremony helper',
    ],
  },
  {
    slug: 'internship',
    name: 'Internship',
    emoji: '🏢',
    description: 'Short-term internship and work placement opportunities',
    subTypes: [
      'Marketing internship',
      'Admin assistant internship',
      'Social media internship',
      'IT support internship',
      'Customer service internship',
      'Research internship',
      'Accounting internship',
      'Event management internship',
      'Content creation internship',
      'Sales internship',
    ],
  },
  {
    slug: 'other',
    name: 'Other',
    emoji: '➕',
    description: 'Anything else that doesn\'t fit the categories above',
    subTypes: [],
  },
];

// ── Helper exports ──

/** Category names only (for dropdowns/filters) */
export const CATEGORY_NAMES = GIG_CATEGORIES.map((c) => c.name);

/** Category names with emojis (for display) */
export const CATEGORY_OPTIONS = GIG_CATEGORIES.map((c) => ({
  value: c.slug,
  label: `${c.emoji} ${c.name}`,
}));

/** Flat list of ALL sub-types across categories */
export const ALL_GIG_SUBTYPES = GIG_CATEGORIES.flatMap((c) => c.subTypes);

/** Skills that students can tag on their profiles */
export const STUDENT_SKILLS = [
  // Typing & Office
  'Typing', 'MS Word', 'MS Excel', 'MS PowerPoint', 'Google Docs', 'Google Sheets',
  'Data Entry', 'Document Formatting',
  // Design & Creative
  'Canva', 'Graphic Design', 'Poster Design', 'Logo Design', 'Figma',
  'Gift Wrapping', 'Hand Lettering',
  // Social Media
  'Social Media Management', 'Instagram', 'TikTok', 'Facebook', 'Twitter/X',
  'WhatsApp Marketing', 'Content Creation',
  // Photography & Video
  'Photography', 'Video Recording', 'Video Editing', 'Livestreaming',
  // People Skills
  'Public Speaking', 'Customer Service', 'Ushering', 'Event Planning',
  'MC/Hosting', 'Crowd Management',
  // Physical
  'Driving', 'Cooking', 'Baking', 'Cleaning', 'Gardening',
  'Moving & Lifting', 'Painting (walls)',
  // Academic
  'Maths Tutoring', 'Science Tutoring', 'English Tutoring', 'French Tutoring',
  'Exam Prep Coaching', 'Research', 'Academic Writing',
  // Writing
  'Writing', 'Proofreading', 'Translation', 'Transcription',
  'CV Writing', 'Copywriting',
  // Tech
  'Web Design', 'Web Development', 'Mobile App Testing', 'Basic IT Support',
  'Phone Setup', 'Printer Setup',
  // Distribution
  'Flyer Distribution', 'Campus Delivery', 'Surveying',
  // Other
  'Babysitting', 'Pet Sitting', 'Dog Walking',
  'Cashier', 'Stock Taking', 'Inventory',
  'Physical Tasks', 'First Aid',
] as const;

export type StudentSkill = (typeof STUDENT_SKILLS)[number];
